// Code generated by mockery v2.45.0. DO NOT EDIT.

package repository

import (
	context "context"

	entity "github.com/MauricioGZ/CRUD-GO/internal/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// DeleteAddressByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteAddressByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAddressByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOrderItemByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteOrderItemByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrderItemByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOrderItemsByOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockRepository) DeleteOrderItemsByOrderID(ctx context.Context, orderID int64) error {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrderItemsByOrderID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProductByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteProductByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) DeleteUserByEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddressesByUserId provides a mock function with given fields: ctx, userId
func (_m *MockRepository) GetAddressesByUserId(ctx context.Context, userId int64) ([]entity.Address, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressesByUserId")
	}

	var r0 []entity.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Address, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.Address); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCategories provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllCategories(ctx context.Context) ([]entity.Categories, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []entity.Categories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Categories, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Categories); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Categories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPermissionsRoles provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllPermissionsRoles(ctx context.Context) ([]entity.PermissionRoles, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPermissionsRoles")
	}

	var r0 []entity.PermissionRoles
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.PermissionRoles, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.PermissionRoles); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PermissionRoles)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllProducts provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllProducts(ctx context.Context) ([]entity.Product, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Product, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllRoles provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllRoles(ctx context.Context) ([]entity.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRoles")
	}

	var r0 []entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetCategoryByID(ctx context.Context, id int64) (*entity.Categories, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *entity.Categories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Categories, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Categories); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Categories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByName provides a mock function with given fields: ctx, name
func (_m *MockRepository) GetCategoryByName(ctx context.Context, name string) (*entity.Categories, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByName")
	}

	var r0 *entity.Categories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Categories, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Categories); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Categories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetOrderByID(ctx context.Context, id int64) (*entity.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderItemsByOrderId provides a mock function with given fields: ctx, orderID
func (_m *MockRepository) GetOrderItemsByOrderId(ctx context.Context, orderID int64) ([]entity.OrderItem, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderItemsByOrderId")
	}

	var r0 []entity.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.OrderItem, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.OrderItem); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderItemsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetOrderItemsByUserID(ctx context.Context, userID int64) ([]entity.OrderItemByUserID, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderItemsByUserID")
	}

	var r0 []entity.OrderItemByUserID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.OrderItemByUserID, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.OrderItemByUserID); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OrderItemByUserID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetOrdersByUserID(ctx context.Context, userID int64) ([]entity.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUserID")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetPaymentByID(ctx context.Context, id int64) (*entity.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByID")
	}

	var r0 *entity.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByOrderID provides a mock function with given fields: ctx, orderID
func (_m *MockRepository) GetPaymentByOrderID(ctx context.Context, orderID int64) (*entity.Payment, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByOrderID")
	}

	var r0 *entity.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Payment, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Payment); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetProductByID(ctx context.Context, id int64) (*entity.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductsByCategoryID provides a mock function with given fields: ctx, categoryID
func (_m *MockRepository) GetProductsByCategoryID(ctx context.Context, categoryID int64) ([]entity.Product, error) {
	ret := _m.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByCategoryID")
	}

	var r0 []entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Product, error)); ok {
		return rf(ctx, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.Product); ok {
		r0 = rf(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertCategory provides a mock function with given fields: ctx, name, description, parentID
func (_m *MockRepository) InsertCategory(ctx context.Context, name string, description string, parentID int64) error {
	ret := _m.Called(ctx, name, description, parentID)

	if len(ret) == 0 {
		panic("no return value specified for InsertCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, name, description, parentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertOrder provides a mock function with given fields: ctx, userID, status, totalPrice
func (_m *MockRepository) InsertOrder(ctx context.Context, userID int64, status string, totalPrice float32) (*int64, error) {
	ret := _m.Called(ctx, userID, status, totalPrice)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrder")
	}

	var r0 *int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, float32) (*int64, error)); ok {
		return rf(ctx, userID, status, totalPrice)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, float32) *int64); ok {
		r0 = rf(ctx, userID, status, totalPrice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, float32) error); ok {
		r1 = rf(ctx, userID, status, totalPrice)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOrderItem provides a mock function with given fields: ctx, orderID, productID, quantity, price
func (_m *MockRepository) InsertOrderItem(ctx context.Context, orderID int64, productID int64, quantity int64, price float32) error {
	ret := _m.Called(ctx, orderID, productID, quantity, price)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrderItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64, float32) error); ok {
		r0 = rf(ctx, orderID, productID, quantity, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertPayment provides a mock function with given fields: ctx, orderId, paymentMethod, amount, paymentDate, status
func (_m *MockRepository) InsertPayment(ctx context.Context, orderId int64, paymentMethod string, amount float32, paymentDate time.Time, status string) error {
	ret := _m.Called(ctx, orderId, paymentMethod, amount, paymentDate, status)

	if len(ret) == 0 {
		panic("no return value specified for InsertPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, float32, time.Time, string) error); ok {
		r0 = rf(ctx, orderId, paymentMethod, amount, paymentDate, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertProduct provides a mock function with given fields: ctx, name, description, price, stock, categoryId, image
func (_m *MockRepository) InsertProduct(ctx context.Context, name string, description string, price float32, stock int64, categoryId int64, image string) error {
	ret := _m.Called(ctx, name, description, price, stock, categoryId, image)

	if len(ret) == 0 {
		panic("no return value specified for InsertProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float32, int64, int64, string) error); ok {
		r0 = rf(ctx, name, description, price, stock, categoryId, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertUser provides a mock function with given fields: ctx, firstName, lastName, email, password, roleID
func (_m *MockRepository) InsertUser(ctx context.Context, firstName string, lastName string, email string, password string, roleID int64) error {
	ret := _m.Called(ctx, firstName, lastName, email, password, roleID)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int64) error); ok {
		r0 = rf(ctx, firstName, lastName, email, password, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveAddress provides a mock function with given fields: ctx, userId, addressType, address, city, state, country, zipCode
func (_m *MockRepository) SaveAddress(ctx context.Context, userId int64, addressType string, address string, city string, state string, country string, zipCode string) error {
	ret := _m.Called(ctx, userId, addressType, address, city, state, country, zipCode)

	if len(ret) == 0 {
		panic("no return value specified for SaveAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string, string, string) error); ok {
		r0 = rf(ctx, userId, addressType, address, city, state, country, zipCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAddressByID provides a mock function with given fields: ctx, id, addressType, address, city, state, country, zipCode
func (_m *MockRepository) UpdateAddressByID(ctx context.Context, id int64, addressType string, address string, city string, state string, country string, zipCode string) error {
	ret := _m.Called(ctx, id, addressType, address, city, state, country, zipCode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddressByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string, string, string) error); ok {
		r0 = rf(ctx, id, addressType, address, city, state, country, zipCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCategoryByID provides a mock function with given fields: ctx, id, name, description, parentID
func (_m *MockRepository) UpdateCategoryByID(ctx context.Context, id int64, name string, description string, parentID int64) error {
	ret := _m.Called(ctx, id, name, description, parentID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategoryByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, int64) error); ok {
		r0 = rf(ctx, id, name, description, parentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProduct provides a mock function with given fields: ctx, name, description, price, stock, categoryId, image, id
func (_m *MockRepository) UpdateProduct(ctx context.Context, name string, description string, price float32, stock int64, categoryId int64, image string, id int64) error {
	ret := _m.Called(ctx, name, description, price, stock, categoryId, image, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float32, int64, int64, string, int64) error); ok {
		r0 = rf(ctx, name, description, price, stock, categoryId, image, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
