// Code generated by mockery v2.45.0. DO NOT EDIT.

package repository

import (
	context "context"

	entity "github.com/MauricioGZ/CRUD-GO/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// DeleteAddressByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteAddressByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAddressByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) DeleteUserByEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddressesByUserId provides a mock function with given fields: ctx, userId
func (_m *MockRepository) GetAddressesByUserId(ctx context.Context, userId int64) ([]entity.Address, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressesByUserId")
	}

	var r0 []entity.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Address, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.Address); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCategories provides a mock function with given fields: ctx
func (_m *MockRepository) GetAllCategories(ctx context.Context) ([]entity.Categories, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []entity.Categories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.Categories, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Categories); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Categories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetCategoryByID(ctx context.Context, id int64) (*entity.Categories, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *entity.Categories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.Categories, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Categories); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Categories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByName provides a mock function with given fields: ctx, name
func (_m *MockRepository) GetCategoryByName(ctx context.Context, name string) (*entity.Categories, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByName")
	}

	var r0 *entity.Categories
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Categories, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Categories); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Categories)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertCategory provides a mock function with given fields: ctx, name, description, parentID
func (_m *MockRepository) InsertCategory(ctx context.Context, name string, description string, parentID int64) error {
	ret := _m.Called(ctx, name, description, parentID)

	if len(ret) == 0 {
		panic("no return value specified for InsertCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, name, description, parentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveAddress provides a mock function with given fields: ctx, userId, addressType, address, city, state, country, zipCode
func (_m *MockRepository) SaveAddress(ctx context.Context, userId int64, addressType string, address string, city string, state string, country string, zipCode string) error {
	ret := _m.Called(ctx, userId, addressType, address, city, state, country, zipCode)

	if len(ret) == 0 {
		panic("no return value specified for SaveAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string, string, string) error); ok {
		r0 = rf(ctx, userId, addressType, address, city, state, country, zipCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveUser provides a mock function with given fields: ctx, firstName, lastName, email, password
func (_m *MockRepository) SaveUser(ctx context.Context, firstName string, lastName string, email string, password string) error {
	ret := _m.Called(ctx, firstName, lastName, email, password)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, firstName, lastName, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAddressByID provides a mock function with given fields: ctx, id, addressType, address, city, state, country, zipCode
func (_m *MockRepository) UpdateAddressByID(ctx context.Context, id int64, addressType string, address string, city string, state string, country string, zipCode string) error {
	ret := _m.Called(ctx, id, addressType, address, city, state, country, zipCode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddressByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, string, string, string) error); ok {
		r0 = rf(ctx, id, addressType, address, city, state, country, zipCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCategoryByID provides a mock function with given fields: ctx, id, name, description, parentID
func (_m *MockRepository) UpdateCategoryByID(ctx context.Context, id int64, name string, description string, parentID int64) error {
	ret := _m.Called(ctx, id, name, description, parentID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategoryByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, int64) error); ok {
		r0 = rf(ctx, id, name, description, parentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
